services:
  - type: web
    name: fyp-web-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    rootDir: FYP-25-S1-09 Mongodb Voice Generate
